# Generated by Django 5.2.15 on 2026-07-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_online_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_connections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
