# Generated by Django 5.2.15 on 2026-07-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_active_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active_connections',
        ),
    ]
