# Generated by Django 5.2.15 on 2026-07-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.room'),
        ),
    ]
