# Generated by Django 5.2.15 on 2026-08-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
